version: '2.1'

services:
  walleter-server:
    image: walleter-server
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js