version: 2
jobs:
  build:
    docker:
    - image: wlsdud2194/node-inyarn:v1

    working_directory: ~/repo

    environment:
    - IS_TEST_MODE: true

    steps:
    - checkout
    - run:
        name: Update-npm
        command: 'sudo npm install -g npm@latest'

    # dependency install
    - restore_cache:
        keys:
        - dependency-cache-{{ checksum "package.json" }}
        - dependency-cache-
        paths:
        - node_modules

    - run:
        name: Install yarn
        command: 'sudo npm install -g yarn'

    - run:
        name: Install pkg
        command: 'yarn'

    - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
        - node_modules

    # test
    - run:
        name: Testing server
        command: 'yarn test'
workflows:
  version: 2
  build:
    jobs:
    - build
